export interface OrderItemTypeTodayPayment {
  PaymentID: any;
  PAYSLNO: any;
  Cdate: string;
  RefNo: string;
  ChequeNo: string;
  PartyID: any;
  PartyName: string;
  Accid: any;
  AccountName: string;
  TransType: string;
  ModeOfPayment: string;
  DbtAmt: any;
  CrdtAmt: any;
  Discount: any;
  DisRemarks: string | null;
  Remarks: string;
  inact: string | null;
  BillAmount: any;
  OthAmount: any;
  OthRemarks: string;
  TotAmt: any;
  PayModel: any;
  Remarks1: string;
  DisAcrel: string | null;
  AprSts: any;
  AprDate: string | null;
  AprUser: string | null;
}

export interface TodayExpenseInterface {
  ACCQRYSTR: null | string;
  AcRel: any;
  Acc1Id: any;
  Acc2Id: any;
  Account1: string;
  Account2: string;
  ActionType: any;
  Amount: any;
  AprDate: string;
  AprDateStr: string;
  AprSts: any;
  AprUser: null | string;
  Cdate: string;
  CdateStr: string;
  DTId: any | string;
  EmpAutoid: any;
  EmpCode: string;
  EmpName: null | string;
  ORDERBY: null | string;
  OrgAutoID: any;
  PayType: string;
  Payment: any;
  Receipt: any;
  RefModule: null | string;
  RefNo: string;
  RefRcdID: any;
  Remarks: string;
  Route: string;
  updatedDate?: any;
  SLNO: any;
  SubHdID: any;
  SubHead: string;
  TRANSTYPE: string;
  UserAutoID: any;
  UserCode: string;
  VehicleNo: string;
}

export interface PartyItemType {
  AccAddress: string;
  AccAddress1: string;
  AccAddress2: string;
  AccAutoID: number;
  AccAutoIDClient: string;
  AccCity: string;
  AccState: string;
  BalColor: string;
  Balance: number;
  Byr_Cd: string;
  Byr_nam: string;
  Groups: string;
  IsDropped: boolean;
  LocAprYN: boolean;
  LocLatLong: string;
  LocationString: string;
  MaxCreditAmount: number;
  MaxCreditDays: number;
  OpBalance: number;
  PartyRemarks: string;
  PhoneNo: string;
  SlNo: number;
  VATNO: string;
}

export interface NewExpenseInterface {
  ACCQRYSTR: string;
  AcRel: number | string;
  Acc1Id: number | string;
  Acc2Id: number | string;
  Account1: string;
  Account2: string;
  ActionType: number | string;
  Amount: number | string;
  Cdate: string; // Assuming this is a string representation of a date
  CdateStr: string;
  DTId: number | string;
  EmpAutoid: number | string;
  EmpCode: string;
  EmpName: string;
  ORDERBY: string;
  OrgAutoID: number | string;
  PayType: string;
  Payment: number | string;
  Receipt: number | string;
  RefModule: string | null;
  RefNo: string;
  RefRcdID: number | string;
  Remarks: string;
  Route: string;
  SLNO: number | string;
  SubHdID: number | string;
  SubHead: string;
  TRANSTYPE: string;
  UserAutoID: number | string;
  UserCode: string;
  VehicleNo: string;
}

export interface NewPaymentInterface {
  Accid: number | null;
  AccountName: string | null;
  BillAmount: number | null;
  Cdate: string | null;
  ChequeNo: string | null;
  CrdtAmt: number | null;
  DbtAmt: number | null;
  DisAcrel: number | null;
  DisRemarks: string | null;
  Discount: number | null;
  ModeOfPayment: string | null;
  OthAmount: number | null;
  OthRemarks: null;
  PAYSLNO: number | null;
  PartyID: number | null;
  PartyName: string | null;
  PayModel: number | null;
  PaymentID: number | null;
  RefNo: string | null;
  Remarks: string | null;
  Remarks1: string | null;
  TotAmt: number | null;
  TransType: string | null;
  inact: null;
  AccAddress: string | null;
}

interface PaymentDetail {
  ActionType: number;
  AutNo: number | string;
  BncCharges: number;
  BounceAcrel: number;
  ChqSts: number;
  DTLMOP: string;
  DtlAccName: string;
  DtlAccid: number;
  DtlChQDated: string;
  DtlChqNo: string;
  DtlRemark: string;
  Entid: number;
  PartyCode: number;
  PayAcrel: number;
  PayCrAmt: number | string;
  PayDrAmt: number;
  PayID: number;
  PayRemarks: string;
  SVRCode: number;
}

export interface NewPaymentTableInterface {
  Accid: number;
  AccountName: string;
  Acrel: number;
  ActionType: number;
  BillAmount: number;
  Cdate: string;
  CdateStr: string;
  ChequeNo: string;
  CrdtAmt: number;
  DbtAmt: number;
  DisAcrel: number;
  ModeOfPayment: string;
  OthAmount: number;
  OthRemarks: string;
  PartyID: number;
  PartyName: string;
  PaymentDetail: PaymentDetail[];
  RefNo: string;
  Remarks: string;
  Remarks1: string;
  TotAmt: number;
}

export interface LocationData {
  EntLocID: string;
  AccAutoID: number;
  CDateStr: string;
  LocLatLong: string;
  LocationString: string;
  LocPlace: string;
  AprUser: string;
  Module: string;
  Reason: string;
  Remarks: string;
}

export interface EmpAttendanceType {
  ActionType: number | null | any;
  AdvAmt: number | null | any;
  AttAmt: number | null | any;
  AttDate: string | null | any;
  AttDateStr: string | null | any;
  AttDys: number | null | any;
  AttFullMins: number | null | any;
  AttMstAmt: number | null | any;
  AttType1: string | null | any;
  AttType2: string | null | any;
  AttValue: number | null | any;
  AttValueStr: string | null | any;
  AttWHMS: string | null | any;
  AttWHrs: number | null | any;
  AttWMins: number | null | any;
  AttWSecs: number | null | any;
  ChkRollAttID: number | null | any;
  Department: string | null | any;
  EmpAutoId: number | null | any;
  EmpCode: string | null | any;
  EmployeeName: string | null | any;
  FTime: string | null | any;
  FullHMS: string | null | any;
  FullMins: number | null | any;
  FullSec: number | null | any;
  FullWHrs: number | null | any;
  FullWMins: number | null | any;
  FullWSecs: number | null | any;
  JOName: string | null | any;
  JONo: number | null | any;
  OTAmt: number | null | any;
  OTFullMins: number | null | any;
  OTHMS: string | null | any;
  OTWHrs: number | null | any;
  OTWMins: number | null | any;
  OTWSecs: number | null | any;
  OrgAutoID: number | null | any;
  PAYID: number | null | any;
  Remarks: string | null | any;
  ToTime: string | null | any;
}

export interface EmpMstrType {
  EMPAUTOID: number | null;
  EmployeeSlNo: number | null;
  EMPCODE: string | null;
  EmployeeName: string | null;
  FatherName: string | null;
  DateofBirthStr: string | null;
  Gender: string | null;
  MOBILENO: string | null;
  EmployeeType: string | null;
  Designation: string | null;
  Department: string | null;
  DOFJOINStr: string | null;
  PhoneNo: string | null;
  EmailAddress: string | null;
  PANNo: string | null;
  ADHARNO: string | null;
  BalAmt: number | null;
  EMPIdentity: string | null;
  PrsAddress0: string | null;
  PrsAddress1: string | null;
  PrsAddress2: string | null;
  PrsDistrict: string | null;
  PrsPIN: string | null;
  PrsState: string | null;
  PerAddress0: string | null;
  PerAddress1: string | null;
  PerAddress2: string | null;
  PerDISTRICT: string | null;
  PerPIN: string | null;
  PerState: string | null;
  SalaryType: number | null;
  BasicRate: number | null;
  OTEMPYN: boolean | null;
  Qualification: string | null;
  Referance1: string | null;
  DOFLeavingStr: string | null;
  Remarks: string | null;
  DRPYN: boolean | null;
}

export interface EmployeeDetailInterface {
  EMPAUTOID: number | string | any;
  SOCID: null | number | string | any;
  ORGCODE: number | string | any;
  EMPID: number | string | any;
  EMPCODE: string;
  EmployeeSlNo: number | string | any;
  SalCode: null | number | string | any;
  Salutation: null | string;
  EmployeeName: string;
  FatherName: string;
  FatherOccupation: null | string;
  PrsAddress0: string;
  PrsAddress1: string;
  PrsAddress2: string;
  PrsDistCode: null | number | string | any;
  PrsDistrict: string;
  PrsStateCode: null | number | string | any;
  PrsState: string;
  PrsNatCode: null | number | string | any;
  PrsNation: null | string;
  PrsPIN: string;
  PayScale: null | string;
  PayscaleCode: number | string | any;
  Designation: string;
  DesigCode: number | string | any;
  Department: string;
  DepCode: null | string;
  TypeCode: null | string;
  EmployeeType: string;
  DateofBirth: string;
  Gender: string;
  DOFJOIN: string;
  DOFREJOIN: null | string;
  DispCode: null | string;
  ESIDispensary: null | string;
  PFAccountNo: null | string;
  PFDOFELG: null | string;
  Pfvolamt: null | number | string | any;
  ESIAccountNo: null | string;
  ESIDOFELG: null | string;
  PFYN: null | string;
  PFEPFYN: boolean;
  PFCPFYN: boolean;
  PFundYn: boolean;
  PFundStartDate: null | string;
  ESIYN: boolean;
  SalaryType: number | string | any;
  PerAddress0: string;
  PerAddress1: string;
  PerAddress2: string;
  PerDistCode: null | number | string | any;
  PerDISTRICT: string;
  PerStateCode: null | number | string | any;
  PerState: string;
  PerNatCode: null | number | string | any;
  PerNATIONALITY: null | string;
  PerPIN: string;
  PhoneNo: string;
  EmailAddress: string;
  BankCode: null | string;
  BankName: null | string;
  BankAccno: null | string;
  ModeOfPay: null | string;
  PANNo: string;
  ContractorYN: boolean;
  ContCode: null | string;
  ContractorName: null | string;
  ShiftCode: null | string;
  ShiftName: null | string;
  YearsOfService: null | number | string | any;
  Grade: null | string;
  Qualification: string;
  DOFIncr: null | string;
  Referance1: string;
  Referance2: null | string;
  Remarks: string;
  DOFLeaving: null | string;
  OTAPPYN: boolean;
  OTEMPYN: boolean;
  OTRate: number | string | any;
  OTTimes: number | string | any;
  OTHourPay: number | string | any;
  OTdaypay: number | string | any;
  TDSCATEGORY: null | string;
  MaritalStatus: null | string;
  MOBILENO: string;
  PFHIGHEREPF: boolean;
  PFHIGHEREPS: boolean;
  EMPLOYEEDISABLED: boolean;
  BANKBRANCH: null | string;
  EMPLOYEECATEGORY: null | string;
  EMPCLASS: null | string;
  EMPSECTION: null | string;
  MOTHERNAME: null | string;
  MSTATUS: null | string;
  WID: boolean;
  SPOUSEOCC: null | string;
  SPOUSEPHONE: null | string;
  SKILLS: null | string;
  Experience: null | string;
  IntDate: null | string;
  PeriodOfempl: null | string;
  lastschool: null | string;
  reasnolast: null | string;
  howdid: null | string;
  whatdo: null | string;
  commitment: null | string;
  ORGAUTOID: number | string | any;
  EMPIdentity: string;
  PFHusFlag: null | string;
  DRPYN: boolean;
  USERID: number | string | any;
  PPNo: null | string;
  PPlaceOfIssue: null | string;
  PPIssueDate: null | string;
  PPExpiryDate: null | string;
  VisaNo: null | string;
  VIsaPlaceOfIssue: null | string;
  VisaIssueDate: null | string;
  VisaExpiryDate: null | string;
  HonoursOrAwards: null | string;
  SportsDetails: null | string;
  LiteracyDetails: null | string;
  DramaticsDetails: null | string;
  MusicOrDanceDetails: null | string;
  OtherActivity: null | string;
  DateOfProbation: null | string;
  DateOfConfirmation: null | string;
  DateofDeath: null | string;
  PayrollYN: null | string;
  Height: null | string;
  Weight: null | string;
  SPName: null | string;
  SPSQualification: null | string;
  SPSDob: null | string;
  SPEmployerDetails: null | string;
  SubTaught: null | string;
  SplDuties: null | string;
  MTNG: null | string;
  Religion: null | string;
  Community: null | string;
  Category: null | string;
  BG: null | string;
  PayGroup: null | string;
  UAN: null | string;
  APPNATURE: null | string;
  ADHARNO: string;
  BasicRate: number | string | any;
  WorkType: null | string;
  BalAmt: number | string | any;
}

export type HandleSubmission = (e: React.FormEvent<HTMLFormElement>) => void;
export type FunctionWithoutArgs = () => any;

export type EmployeeDDInterface = {
  EMPAUTOID: number;
  EMPCODE: string;
  EmployeeName: string;
  DRPYN: boolean;
};

export interface ResponseInterface {
  ActionType: number;
  ErrorCode: string;
  ErrorMessage: string;
  JSONData1: string;
  JSONData1Remarks: string;
  JSONData2?: string;
  JSONData2Remarks?: string;
  JSONData3?: string;
  JSONData3Remarks?: string;
  JSONData4?: string;
  JSONData4Remarks?: string;
  JSONData5?: string;
  JSONData5Remarks?: string;
  SuccessMessage?: string;
}

export type AccountLedgerItemType = {
  ACCORGAUTOID: number;
  ACCOUNT: string;
  ACCQRYSTR: string | null;
  ACREL: number;
  ActionType: number;
  BALANCE: number;
  BLLNO: string;
  BalLstLateDays: number;
  BalLstPayDate: string | null;
  BalPayAdjAmt: number;
  BalPending: string | null;
  BalanceAmt: number;
  BalanceColor: string;
  CCRAMOUNT: string;
  CDRAMOUNT: string;
  CLR: string;
  CRACCOUNT: string;
  CRAMOUNT: number;
  CRBALANCE: number;
  CRCON: string;
  CT_DT: string;
  CT_DTStr: string;
  CnclYn: boolean;
  DESC1: string;
  DESC2: string;
  DESC3: string;
  DESC4: string;
  DESC5: string;
  DRACCOUNT: string;
  DRAMOUNT: number;
  DRBALANCE: number;
  DRCR: number;
  DelYn: boolean;
  DrpYn: boolean;
  ISSREC: string;
  LstLateDays: number;
  LstPayDate: string;
  ORDERBY: string | null;
  OrgAutoID: number;
  PayAdjAmt: number;
  Pending: string | null;
  REFNO: string | null;
  REFTYPE: string | null;
  RefModule: string;
  RefModuleID: number;
  TRANSTYPE: string;
  VchAutoID: number;
  acid: number;
  autno: number;
  chqno: string | null;
  crid: number;
  drid: number;
  post: boolean;
  prtid: number;
  seno: number;
  vchno: number;
};

export type SelectedPartyDetailsInterface = {
  ACCORGAUTOID: number;
  ACCOUNTNO: string;
  ACCQRYSTR: string | null;
  ACTYP: string;
  AccAddress: string;
  AccAddress1: string;
  AccAddress2: string;
  AccAutoID: number;
  AccCity: string;
  AccState: string;
  AccountLedger: AccountLedgerItemType[];
  ActionType: number;
  BALTYPE: number;
  Byr_Cd: string | null;
  Byr_nam: string;
  CLBalColor: string;
  CLBalance: number;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CMNT: string | null;
  CNTRY1: string;
  CONTACTPERSON: string;
  CONTACTTITLE: string;
  COPBLS: number;
  CSTNO: string;
  CUSTYPE: string;
  EMAIL: string;
  EMAIL2: string;
  FOB1: string;
  GROUPS: string;
  GRPHANDLE: string;
  GRPUNDER: string;
  ISDROPPED: boolean;
  ImpCode: number;
  LCNO: string;
  LEDTYPE: string;
  LTYPE: string;
  LateBillsAmount: number;
  MNGRP: string;
  MSSB: number;
  MaxCreditAmount: number;
  MaxCreditDays: number;
  NATURE: string;
  NofLateBills: number;
  NofPendingBills: number;
  OPBLS: number;
  OPCRBLC: number;
  OPDRBLC: number;
  ORDERBY: string | null;
  Old_Byr_nam: string | null;
  OrgAutoid: number;
  PANNO: string;
  PLBAL: string;
  PhoneNo: string;
  PinCode: string;
  REFNO1: string;
  REFNO2: string;
  REFNO3: string;
  RELID: number;
  RELTYPE: string;
  STNO: string;
  SVRUPDYN: number;
  TDSYN: boolean;
  TRANSPORT: string;
  VATNO: string;
  WORKTYPE: string;
  pcap: number;
  sbgrp: string;
};

export type StaffLocationInterfaceOnMap = {
  EntLocID: number;
  AccAutoID: number;
  CDate: string;
  lat: number;
  long: number;
  LocLatLong: string;
  LocationString: string;
  LocPlace: string;
  AprUser: string;
  Module: string;
  Reason: string;
  Remarks: string;
};

export interface BrandMasterDetailsInterface {
  ActionType: number;
  CLIENTPRFIX: string | null;
  CLIENTTRANSID: string | null;
  GroupType: string;
  GrpID: number;
  IsActive: boolean;
  ORGAUTOID: number;
  OldGroup: string | null;
  ProductGroup: string;
  SVRUPDYN: number;
}

export interface OrderItemTypeTodayOrder {
  AccPartyID: number;
  AccPartyName: string;
  ActionType: number;
  AddedDate: string;
  CGSTAmt: number;
  CardPay: number;
  CashPay: number;
  CessAmt: number;
  ChequePay: number;
  Counter: string;
  CreditPay: number;
  DelDate: string;
  DelDateStr: string;
  DelPerson: string;
  DelPhoneNo: string;
  DelRemarks: string;
  DelStatus: string;
  DeliveryCharge: number;
  DiscountAmt: number;
  EntryDateTime: string;
  EntryDateTimeStr: string;
  FlatDiscount: number;
  FullOrderAmount: number;
  GPSLDetails: string;
  GPSLocation: string;
  GSTAmt: number;
  GrossAmount: number;
  IGSTAmt: number;
  IsDropped: boolean;
  ModeOfDel: string;
  NetAmount: number;
  OnlinePay: number;
  OrdYear: number;
  OrderAddress: string;
  OrderAddress2: string;
  OrderAmount: number;
  OrderCity: string;
  OrderCountry: string;
  OrderDate: string;
  OrderDateStr: string;
  OrderDiscountAmt: number;
  OrderDist: string;
  OrderEmailAddress: string;
  OrderID: number;
  OrderModeOfDel: string;
  OrderNo: number;
  OrderPhoneNo: string;
  OrderPin: string;
  OrderPlace: string;
  OrderPostOffice: string;
  OrderRemarks: string;
  OrderSource: string;
  OrderState: string;
  PartyClientID: number;
  PartyID: number;
  PartyName: string;
  RefundAmt: number;
  RefundRemarks: string;
  Remarks: string;
  RofAmt: number;
  SGSTAmt: number;
  SeatNos: string;
  SvrBillNo: number;
  SvrCode: number;
  TotAmount: number;
  TotItemDiscount: number;
  TransactionNo: string;
  UPIPay: number;
  UserAutoID: number;
  UserCode: string;
  VehicleNo: string;
}

export interface OrderTransactionInterface {
  ActionType: number;
  DelFlag: number;
  Disper: string;
  FreeQty: number;
  ItemDisAmount: number;
  OrderAmount: number;
  OrderID: number;
  OrderQty: number;
  OrderRate: number;
  OrderRemarks: string;
  OrderTransID: number;
  PLUCODE: string;
  STKSVRSTOCK: number;
  STOCKCOLOR: string;
  STOCKLastRate: number;
  STOCKMRP: number;
  STOCKSalePrice: number;
  STOCKWSPrice: number;
  SVRSTKID: number;
  SaleRate: number;
  SvrEntid: number;
  TotQty: number;
  TrnAmount: number;
  TrnCGSTAmt: number;
  TrnCGSTPer: number;
  TrnCessAmt: number;
  TrnCessPer: number;
  TrnGSTAmt: number;
  TrnGSTPer: number;
  TrnGrossAmt: number;
  TrnIGSTAmt: number;
  TrnIGSTPer: number;
  TrnNetAmount: number;
  TrnSGSTAmt: number;
  TrnSGSTPer: number;
  itm_CD: number;
  itm_NAM: string;
}

export type ProductGetSelectedProductDetails = {
  ALQTY: number;
  ActionType: number;
  AddedBy: number;
  BARCODEID: string;
  BATCHNO: string;
  Barcode: string;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CatID: number;
  Category: string;
  ClrGroup: string;
  Cost: number;
  CostPrice: number;
  CounterNo: string;
  DGID: number;
  DGNDX: number;
  DROPPED: boolean;
  Department: string;
  DesignCode: string | null;
  DesignNo: number;
  DisplayGrp: string;
  EXPDTYN: boolean;
  FinalStock: number;
  FolderName: string;
  FreeQty: number;
  GENNAME: string;
  GSTITMCD: number;
  IColor: string;
  ID: number;
  ISize: string;
  Icompany: string;
  ImageDescription: string;
  ImageFile: string;
  ImageFiles: string;
  ImagePath: string;
  IsActive: boolean;
  LastDate: string;
  LastRate: number;
  LoosQty: number;
  LooseRate: number;
  MRP: number;
  Material: string;
  NUMBERPERCASE: number;
  NUMBERPERCASE1: number;
  ORGAUTOID: number;
  ORGCODE: number;
  OldHsnCode: number;
  OrderCesPer: number;
  PLUCODE: string;
  PNID: number;
  PRERSUPL: string;
  ProductBL: string;
  ProductDupatta: string;
  ProductGroup: string;
  ProductLining: string;
  ProductSL: string;
  ProductStyle: string;
  ProductTL: string;
  ProductWork: string;
  PrtRecQty: number;
  PurPrice: number;
  QryStr: string;
  QtnMargPer: number;
  QtnMargRate: number;
  RTLProfitPer: number;
  RegistrationID: number;
  Remarks1: string;
  Remarks2: string;
  Remarks3: string;
  STKCGSTRate: number;
  STKDIVNUM: number;
  STKGSTRate: number;
  STKHSNCode: number;
  STKIGSTRate: number;
  STKSGSTRate: number;
  STKSVRSTOCK: number;
  STOCKCOLOR: string;
  SUPLID: number;
  SVRENTID: number;
  SVRSTKID: number;
  SVRUPDYN: number;
  SaleDisPer: number;
  SalePrice: number;
  SizeID: number;
  Stk_Opn_Rate: number;
  Stk_opn: number;
  Stk_opn2: number;
  StockType: string;
  SubCatID: number;
  SubCategory: string;
  TYPE: string;
  TransactionID: number;
  UNITS: string;
  UNITS1: string;
  VatMaster: string;
  VatMasterOut: string;
  WSPrice: number;
  WSProfitPer: number;
  YouTubeLink: string;
  billno: number;
  itm_CD: number;
  itm_NAM: string;
  ordertype: number;
  pickerValue: string;
  subgrp: string;
  total: number;
};

export interface OrderDetailsInterface {
  AccPartyID: number;
  AccPartyName: string;
  ActionType: number;
  AddedDate: string;
  CGSTAmt: number;
  CessAmt: number;
  DelDate: string;
  DelDateStr: string;
  DiscountAmt: number;
  EntryDateTime: string;
  FlatDiscount: number;
  FullOrderAmount: number;
  GSTAmt: number;
  GrossAmount: number;
  IGSTAmt: number;
  NetAmount: number;
  OrderDate: string;
  OrderDateStr: string;
  OrderID: number;
  OrderNo: number;
  OrderSource: string;
  PartyClientID: number;
  PartyID: number;
  PartyName: string;
  Remarks: string;
  RofAmt: number;
  SGSTAmt: number;
  TotAmount: number;
  TotItemDiscount: number;
  UserAutoID: number;
  UserCode: string;
  VehicleNo: string;
}

export interface SalesListInterface {
  ACREL: number;
  AGentAmt: number;
  AcaStart: number;
  AccLinkParty: boolean;
  ActionType: number;
  AddedBy: number;
  Addition: number;
  AgentCode: number;
  AgentName: string;
  AmtExclRebate: number;
  BAL: number;
  BILLAMOUNT: number;
  BILLQRYSTR: string | null;
  BILLTYPE: string;
  BLLCGSTAmt: number;
  BLLGSTAmt: number;
  BLLIGSTAmt: number;
  BLLSGSTAmt: number;
  BLLTaxableAmt: number;
  BillCessTaxableAmt: number;
  BillDate: string;
  BillDateStr: string;
  BillEstimateAmount: number;
  BillLbrChAmt: number;
  BillProfitAmount: number;
  BillTransID: number;
  BillTypeID: number;
  BillYear: number;
  BillingSeqID: number;
  BillingSeqType: string;
  BlankSalesItems: SalesBlankItemInterface;
  CHLNO: string;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CMPRefNo: number;
  CRAMT: number;
  CRDATE: string;
  CRDays: number;
  CRNO: string;
  CSTPER: number;
  CardPay: number;
  CardPayAcc: string;
  CashPay: number;
  CashPayAcc: string;
  ChequePay: number;
  ChequePayAcc: string;
  ComPostID: number;
  CommPaidAmt: number;
  CommPaidRem: string;
  CommPaidYN: boolean;
  ConsigneeAddress: string;
  ConsigneeAddress1: string;
  ConsigneeGSTNum: string;
  ConsigneeName: string;
  CounterNo: string;
  CreditPay: number;
  CustID: number;
  DRAMT: number;
  Deduction: number;
  DelPerson: string;
  DisRemarks: string;
  Drblamt: number;
  EIAckDate: string;
  EIAckno: string;
  EINVTYPE: number;
  EIirn: string;
  EMPID: number;
  EWAYBILLDATE: string;
  EWAYBILLNO: string;
  EWBValDate: string;
  EWBYN: boolean;
  EntryMode: number;
  EstiMateRof: number;
  FRTax: number;
  FRTaxPer: number;
  GrsAmtSR: number;
  IsActive: boolean;
  ItmDiscount: number;
  MNLYN: boolean;
  MOTIndex: number;
  ModeOfPay: string;
  ModeofTax: string;
  ModifyBy: number;
  NOSALE: number;
  NetAmount: number;
  NetAmtSR: number;
  NofBales: string;
  NofItms: number;
  ORDERBY: string | null;
  ORGAUTOID: number;
  ORGCODE: number;
  OnlinePay: number;
  OnlinePayAcc: string;
  OrdYear: number;
  OrderID: number;
  OrderNO: number;
  OrderSource: string;
  OtherAdd: number;
  OtherAddRem: string;
  OtherDed: number;
  OtherDedRem: string;
  PAID: number;
  POSTAMOUNT: number;
  PUSALEType: string;
  PackingCharges: number;
  PartyName: string;
  PartyRefno: string;
  PayDiscount: number;
  PaymentStatus: string;
  Purbillno: string;
  QRImage: string | null;
  ROFAMT: number;
  ReceiverAddress: string;
  ReceiverAddress1: string;
  ReceiverGSTNum: string;
  ReceiverName: string;
  SVRUPDYN: number;
  SalesItems: SalesBlankItemInterface[];
  SalesPerson: string;
  SalesUser: string;
  SalesVATItems: any;
  SeatNos: string;
  SeleBillYN: boolean;
  State1: string;
  State2: string;
  StateCode1: number;
  StateCode2: number;
  SubRcptNo: number;
  SvrCode: number;
  TCSAmt: number;
  TCSOn: number;
  TCSPer: number;
  TPTFreight: string;
  TPTLRRRNO: string;
  TPTMode: string;
  TPTWeight: string;
  TotQty: number;
  TotalCost: number;
  TransVehtype: string;
  Transdist: string;
  Transdocdt: string;
  Transdocno: string;
  Transmode: string;
  Transport: string;
  TransportCharges: number;
  TransportID: number;
  TransportName: string;
  UPIPay: number;
  UPIPayAcc: string;
  VatAmt: number;
  VatAmtSR: number;
  VehRoute: string;
  address0: string;
  address1: string;
  balamt: number;
  billno: number;
  code: number;
  crblamt: number;
  deltime: string;
  discount: number;
  disper: string;
  grsttl: number;
  inact: boolean;
  lesdsamt: number;
  ordtime: string;
  partycode: number;
  phoneno: string;
  remarks: string;
  sts: string | null;
  taxamt: number;
}

export type SalesBlankItemInterface = {
  ActionType: number;
  AddRofamt: number;
  AddedBy: number;
  Amount: number;
  BILLQRYSTR: string | null;
  BarcodeId: string;
  BatchId: number;
  BatchNo: string;
  BillNo: number;
  BillTypeID: number;
  BllOthAddamt: number;
  BllOthDedamt: number;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CMPRefNo: number;
  CessPer: number;
  ChallanNo: string;
  ColorCost: number;
  DedDisrofamt: number;
  DelFlag: number;
  DelSts: number;
  Disamt: number;
  Disper: string;
  DmgQty: number;
  EXPDTYN: boolean;
  EstimateAmount: number;
  EstimateRate: number;
  ExpDate: string;
  ExpDateStr: string;
  FTDisAmt: number;
  FTDisPer: string;
  Flag: string;
  FreeAmount: number;
  FreeQty: number;
  GSTITMCD: number;
  Grsamt: number;
  IsActive: boolean;
  IssQtyStr: string;
  Issqty1: number;
  ItemMRP: number;
  ItemTaxableAmt: number;
  ItemWSPrice: number;
  ItmCostPrice: number;
  ItmFRTax: number;
  ItmOthAddAmt: number;
  ItmOthDedAmt: number;
  ItmSaleDisPer: number;
  ItmSalePrice: number;
  ItmTotCost: number;
  ItmpftPer: number;
  ItmwspftPer: number;
  LbrChAmt: number;
  LbrChPer: string;
  MFGCode: string;
  ModifyBy: number;
  NUMBERPERCASE: number;
  NetAmount: number;
  NetNVAT: number;
  ORGAUTOID: number;
  OrgCode: number;
  Purbillno: number;
  Qty: number;
  Qty1: number;
  QtyStr: string | null;
  RWSlNo: number;
  Rate: number;
  Rate1: number;
  RateLessDis: number;
  RcptSourceID: number;
  RebateAmt: number;
  RebatePer: number;
  RecQtyStr: string;
  Recqty: number;
  Recqty1: number;
  Refno: number;
  Remarks: string;
  SCostPrice: number;
  SMRP: number;
  STradePrice: number;
  SVRSTKID: number;
  SelYN: boolean;
  Sets: string;
  StkCostPrice: number;
  StkQtnPer: number;
  StkQtnRate: number;
  StkSalePrice: number;
  SubUnitDetails: string;
  SvrCode: number;
  SvrEntid: number;
  TYPE: string | null;
  TotBllAmt: number;
  TotCostAdd: number;
  TotCostDed: number;
  Transtyp: string;
  TrnCGSTAmt: number;
  TrnCGSTRate: number;
  TrnGSTAmt: number;
  TrnGSTRate: number;
  TrnIGSTAmt: number;
  TrnIGSTRate: number;
  TrnSGSTAmt: number;
  TrnSGSTRate: number;
  UNITS: string;
  VatAmt: number;
  VatPer: number;
  Vatmaster: string;
  cdate: string;
  cdateStr: string | null;
  code: number;
  entid: number;
  exqty: number;
  issqty: number;
  itm_CD: number;
  itm_NAM: string;
  itmtyp: number;
  ndx: number;
  ordid: number;
  party: string;
  partycode: number;
  stonepcs: number;
  stonepkts: number;
  transid: number;
};

export type SalesDetailsDataInterface = {
  ACREL: number;
  AGentAmt: number;
  AcaStart: number;
  AccLinkParty: boolean;
  ActionType: number;
  AddedBy: number;
  Addition: number;
  AgentCode: number;
  AgentName: string;
  AmtExclRebate: number;
  BAL: number;
  BILLAMOUNT: number;
  BILLQRYSTR: string | null;
  BILLTYPE: string;
  BLLCGSTAmt: number;
  BLLGSTAmt: number;
  BLLIGSTAmt: number;
  BLLSGSTAmt: number;
  BLLTaxableAmt: number;
  BillCessTaxableAmt: number;
  BillDate: string;
  BillDateStr: string;
  BillEstimateAmount: number;
  BillLbrChAmt: number;
  BillProfitAmount: number;
  BillTransID: number;
  BillTypeID: number;
  BillingSeqID: number;
  BillingSeqType: string;
  BlankSalesItems: SalesBlankItemInterface;
  CHLNO: string;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CMPRefNo: number;
  CRAMT: number;
  CRDATE: string;
  CRDays: number;
  CRNO: string;
  CSTPER: number;
  ComPostID: number;
  CommPaidAmt: number;
  CommPaidRem: string;
  CommPaidYN: boolean;
  ConsigneeAddress: string;
  ConsigneeAddress1: string;
  ConsigneeGSTNum: string;
  ConsigneeName: string;
  CounterNo: string;
  CustID: number;
  DRAMT: number;
  Deduction: number;
  DelPerson: string;
  DisRemarks: string;
  Drblamt: number;
  EIAckDate: string;
  EIAckno: string;
  EINVTYPE: number;
  EIirn: string;
  EMPID: number;
  EWAYBILLDATE: string;
  EWAYBILLNO: string;
  EWBValDate: string;
  EWBYN: boolean;
  EntryMode: number;
  EstiMateRof: number;
  FRTax: number;
  FRTaxPer: number;
  GrsAmtSR: number;
  IsActive: boolean;
  ItmDiscount: number;
  MNLYN: boolean;
  MOTIndex: number;
  ModeOfPay: string;
  ModeofTax: string;
  ModifyBy: number;
  NOSALE: number;
  NetAmount: number;
  NetAmtSR: number;
  NofBales: string;
  NofItms: number;
  ORDERBY: string | null;
  ORGAUTOID: number;
  ORGCODE: number;
  OtherAdd: number;
  OtherAddRem: string;
  OtherDed: number;
  OtherDedRem: string;
  PAID: number;
  POSTAMOUNT: number;
  PUSALEType: string;
  PackingCharges: number;
  PartyName: string;
  PartyRefno: string;
  PayDiscount: number;
  Purbillno: string;
  QRImage: string | null;
  ROFAMT: number;
  ReceiverAddress: string;
  ReceiverAddress1: string;
  ReceiverGSTNum: string;
  ReceiverName: string;
  SVRUPDYN: number;
  SalesItems: SalesBlankItemInterface[];
  SalesPerson: string;
  SalesVATItems: string | null;
  SeleBillYN: boolean;
  State1: string;
  State2: string;
  StateCode1: number;
  StateCode2: number;
  SubRcptNo: number;
  SvrCode: number;
  TPTFreight: string;
  TPTLRRRNO: string;
  TPTMode: string;
  TPTWeight: string;
  TotalCost: number;
  TransVehtype: string;
  Transdist: string;
  Transdocdt: string;
  Transdocno: string;
  Transmode: string;
  Transport: string;
  TransportCharges: number;
  TransportID: number;
  TransportName: string;
  VatAmt: number;
  VatAmtSR: number;
  VehRoute: string;
  address0: string;
  address1: string;
  balamt: number;
  billno: number;
  code: number;
  crblamt: number;
  deltime: string;
  discount: number;
  disper: string;
  grsttl: number;
  inact: boolean;
  lesdsamt: number;
  ordtime: string;
  partycode: number;
  phoneno: string;
  remarks: string;
  sts: string;
  taxamt: number;
};

export interface CardamomTransaction {
  GCRID: number;
  CompRefNo: number;
  Ndx: number;
  Cdate: string;
  RefNo: string;
  PartyID: number;
  PartyName: string;
  GCRecQty: number;
  Rate: number;
  Works: number;
  ProcAmount: number;
  GCRecRemarks: string;
  StkDate: string;
  StkQty: number;
  ProcRatio: string;
  StockLocation: string;
  DriedYN: boolean;
  DelDate: string;
  DelRemarks: string;
  DelQty: number;
  DelYN: boolean;
  ReceiptAmount: number;
  ReceiptRemarks: string;
  PaidYn: boolean;
  COMemID: number;
  COMemName: string | null;
}

export interface GreenCardamomReceiptData {
  CdateStr: string;
  CompRefNo: number;
  GCRID: number;
  GCRecQty: number;
  GCRecRemarks: string;
  PartyID: number;
  PartyName: string;
  ProcAmount: number;
  Rate: number;
  ReceiptAmount: number;
  ReceiptRemarks: string;
  RefNo: string;
}

export type TransactionInterface = {
  ActionType: number;
  COMemID: number;
  COMemName: string;
  Cdate: string; // "/Date(1740643200000-0800)/" format
  CdateStr: string;
  CompRefNo: number;
  DelDate: string; // "/Date(1740643200000-0800)/" format
  DelDateStr: string;
  DelQty: number;
  DelRemarks: string;
  DelYN: boolean;
  DriedYN: boolean;
  GCRID: number;
  GCRecQty: number;
  GCRecRemarks: string;
  Ndx: number;
  PaidYn: boolean;
  PartyID: number;
  PartyName: string;
  ProcAmount: number;
  ProcRatio: string;
  Rate: number;
  ReceiptAmount: number;
  ReceiptRemarks: string;
  RefNo: string;
  StkDate: string; // "/Date(1740643200000-0800)/" format
  StkDateStr: string;
  StkQty: number;
  StockLocation: string;
  Works: number;
};

export interface OrganizationConfig {
  ACAEND: number;
  ACASTART: number;
  ATT: number;
  AccGroupType: number;
  ActionType: number;
  BANKACCNO: string;
  BULKSMSHISTORY: boolean;
  BarCodeLabelType: number;
  BarcodePageType: number;
  CHKSMSNO: boolean;
  CheckOutTime: string | null;
  DRWOPNCOM: string;
  DefMailTo: string;
  FAX: string;
  LVSTARTMODE: number;
  LinkSalesToAddressBook: boolean;
  MOPayBillingNo: boolean;
  MailCredentialsID: string;
  MailCredentialsPass: string;
  MailFrom: string;
  MailHost: string;
  MailPort: number;
  ORGADDRESS: string;
  ORGAUTOID: number;
  ORGCITY: string;
  ORGCODE: number;
  ORGDISPLAYNAME: string;
  ORGDISTRICT: string;
  ORGNAME: string;
  ORGNATION: string;
  ORGPLACE: string;
  ORGREGNO: string;
  ORGSTATE: string;
  ORGSTREET: string;
  OthItmCode: number;
  PANNO: string | null;
  PARTYRATESAVE: number;
  PDPORT: number;
  PH: string;
  PLUCODEPRX: string;
  PLUCODETYPE: number;
  POSTSMS: boolean;
  PRTPORT: string;
  PUSHOWBTCH: boolean;
  PUSHOWDIS: boolean;
  PUSHOWFLAG: boolean;
  PUSHOWFREE: boolean;
  PUSHOWLOOSE: boolean;
  PUSHOWMFRC: boolean;
  PUSHOWMRP: boolean;
  PUSHOWREM: boolean;
  PUSHOWTP: boolean;
  PUSHOWVAT: boolean;
  PuNavType: number;
  RateNCostingType: number;
  SASHOWBTCH: boolean;
  SASHOWDIS: boolean;
  SASHOWFLAG: boolean;
  SASHOWFREE: boolean;
  SASHOWLOOSE: boolean;
  SASHOWMFRC: boolean;
  SASHOWMRP: boolean;
  SASHOWREM: boolean;
  SASHOWTP: boolean;
  SASHOWVAT: boolean;
  SMSDomainName: string;
  SMSFooter: string;
  SMSHeader: string;
  SMSPassWord: string;
  SMSProvider: number;
  SMSRATE: number;
  SMSSID: string;
  SMSUserName: string;
  SOCID: number;
  SPLS: string;
  STKRPERRW: number;
  SVRUPDYN: boolean;
  SaleNavType: number;
  SalesRateType: number;
  StateCode: number;
  TCOMPANY: string;
  TINNO: string;
  VATNO: string;
  WEBsite: string;
  brach: string | null;
  director: string;
  email: string;
  wof1: boolean;
  wof2: boolean;
}

export type PartyLedgerEntryFullInterface = {
  ACCORGAUTOID: number;
  ACCOUNT: string;
  ACCQRYSTR: string | null;
  ACREL: number;
  ActionType: number;
  BALANCE: number;
  BLLNO: string | null;
  BalLstLateDays: number;
  BalLstPayDate: string | null;
  BalPayAdjAmt: number;
  BalPending: string | null;
  BalanceAmt: number;
  BalanceColor: string | null;
  CCRAMOUNT: string;
  CDRAMOUNT: string;
  CLR: string;
  CRACCOUNT: string | null;
  CRAMOUNT: number;
  CRBALANCE: number;
  CRCON: string | null;
  CT_DT: string;
  CT_DTStr: string;
  CnclYn: boolean;
  DESC1: string | null;
  DESC2: string | null;
  DESC3: string | null;
  DESC4: string | null;
  DESC5: string | null;
  DRACCOUNT: string | null;
  DRAMOUNT: number;
  DRBALANCE: number;
  DRCR: number;
  DelYn: boolean;
  DrpYn: boolean;
  ISSREC: string | null;
  LstLateDays: number;
  LstPayDate: string;
  ORDERBY: string | null;
  OrgAutoID: number;
  PayAdjAmt: number;
  Pending: string | null;
  PendingAmount: number;
  REFNO: string | null;
  REFTYPE: string | null;
  RefModule: string | null;
  RefModuleID: number;
  TRANSTYPE: string;
  VchAutoID: number;
  acid: number;
  autno: number;
  chqno: string | null;
  crid: number;
  drid: number;
  post: boolean;
  prtid: number;
  seno: number;
  vchno: number;
};

export type partyLedgerDataInterface = {
  ACCORGAUTOID: number;
  ACCOUNTNO: string;
  ACCQRYSTR: string | null;
  ACTYP: string;
  AccAddress: string;
  AccAddress1: string;
  AccAddress2: string;
  AccAutoID: number;
  AccCity: string;
  AccState: string;
  AccountLedger: PartyLedgerEntryFullInterface[];
  ActionType: number;
  BALTYPE: number;
  Byr_Cd: string;
  Byr_nam: string;
  CLBalColor: string;
  CLBalance: number;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CMNT: string;
  CNTRY1: string;
  CONTACTPERSON: string;
  CONTACTTITLE: string;
  COPBLS: number;
  CSTNO: string;
  CUSTYPE: string;
  EMAIL: string;
  EMAIL2: string;
  FOB1: string;
  GROUPS: string;
  GRPHANDLE: string;
  GRPUNDER: string;
  ISDROPPED: boolean;
  ImpCode: number;
  LCNO: string;
  LEDTYPE: string;
  LTYPE: string;
  LateBillsAmount: number;
  MNGRP: string;
  MSSB: number;
  MaxCreditAmount: number;
  MaxCreditDays: number;
  NATURE: string;
  NofLateBills: number;
  NofPendingBills: number;
  OPBLS: number;
  OPCRBLC: number;
  OPDRBLC: number;
  ORDERBY: string | null;
  Old_Byr_nam: string | null;
  OrgAutoid: number;
  PANNO: string;
  PLBAL: string;
  PhoneNo: string;
  PinCode: string;
  REFNO1: string;
  REFNO2: string;
  REFNO3: string;
  RELID: number;
  RELTYPE: string;
  STNO: string;
  SVRUPDYN: number;
  TDSYN: boolean;
  TRANSPORT: string;
  VATNO: string;
  WORKTYPE: string;
  pcap: number;
  sbgrp: string;
};
