export type RestuarantProductInterface = {
  ClrGroup: string | null;
  Department: string;
  DisplayGrp: string;
  FinalStock: string;
  GENNAME: string;
  GSTITMCD: number;
  IColor: string | null;
  ISize: string;
  Icompany: string;
  ImageFile: string;
  ImageFiles: any | null;
  MRP: string;
  Material: string;
  PLUCODE: string;
  PPrice: string;
  PRERSUPL: string;
  ProductGroup: string;
  STKCGSTRate: number;
  STKGSTRate: number;
  STKHSNCode: number;
  STKIGSTRate: number;
  STKSGSTRate: number;
  SVRSTKID: string;
  SalePrice: string;
  TYPE: string;
  UNITS: string;
  UNITS1: string;
  WSPrice: string;
  itm_CD: string;
  itm_NAM: string;
  subgrp: string;
};

export type FoodSelectedInterface = {
  name: string;
  qty: number;
  rate: number;
  category: string;
  subCategory: string;
  img: string;
};

export interface StockItemType {
  ClrGroup: string | null;
  Department: string;
  DisplayGrp: string;
  FinalStock: string;
  GENNAME: string;
  GSTITMCD: number;
  IColor: string | null;
  ISize: string;
  Icompany: string;
  ImageFile: string;
  ImageFiles: string;
  MRP: string;
  Material: string;
  PLUCODE: string;
  PPrice: string;
  PRERSUPL: string;
  ProductGroup: string;
  STKCGSTRate: number;
  STKGSTRate: number;
  STKHSNCode: number;
  STKIGSTRate: number;
  STKSGSTRate: number;
  SVRSTKID: string;
  SalePrice: string;
  TYPE: string;
  UNITS: string;
  UNITS1: string;
  WSPrice: string;
  itm_CD: string;
  itm_NAM: string;
  subgrp: string;
}

export type ProductImage = {
  ActionType: number;
  ImageLocation: string | null;
  ImageName: string;
  ImageType: string;
  ImgEntID: number;
  ImgGroup: string;
  ImgRemarks: string;
  SVRSTKID: number;
};

export interface RestoBlankItemInterface {
  ActionType: number;
  DelFlag: number;
  Disper: string;
  FreeQty: number;
  ItemDisAmount: number;
  OrderAmount: number;
  OrderID: number;
  OrderQty: number;
  OrderRate: number;
  OrderRemarks: string;
  OrderTransID: number;
  PLUCODE: string;
  STKSVRSTOCK: number;
  STOCKCOLOR: string;
  STOCKLastRate: number;
  STOCKMRP: number;
  STOCKSalePrice: number;
  STOCKWSPrice: number;
  SVRSTKID: number;
  SaleRate: number;
  SvrEntid: number;
  TotQty: number;
  TrnAmount: number;
  TrnCGSTAmt: number;
  TrnCGSTPer: number;
  TrnCessAmt: number;
  TrnCessPer: number;
  TrnGSTAmt: number;
  TrnGSTPer: number;
  TrnGrossAmt: number;
  TrnIGSTAmt: number;
  TrnIGSTPer: number;
  TrnNetAmount: number;
  TrnSGSTAmt: number;
  TrnSGSTPer: number;
  itm_CD: number;
  itm_NAM: string;
}

export interface RestoOrderDetailsInterface {
  AccPartyID: number;
  AccPartyName: string;
  ActionType: number;
  AddedDate: string;
  CGSTAmt: number;
  CardPay: number;
  CashPay: number;
  CessAmt: number;
  ChequePay: number;
  Counter: string;
  CreditPay: number;
  DelDate: string;
  DelDateStr: string;
  DelPerson: string;
  DelPhoneNo: string;
  DelRemarks: string;
  DelStatus: string;
  DeliveryCharge: number;
  DiscountAmt: number;
  EntryDateTime: string;
  EntryDateTimeStr: string;
  FlatDiscount: number;
  FullOrderAmount: number;
  GPSLDetails: string;
  GPSLocation: string;
  GSTAmt: number;
  GrossAmount: number;
  IGSTAmt: number;
  IsDropped: boolean;
  ModeOfDel: string;
  NetAmount: number;
  OnlinePay: number;
  OrdYear: number;
  OrderAddress: string;
  OrderAddress2: string;
  OrderAmount: number;
  OrderCity: string;
  OrderCountry: string;
  OrderDate: string;
  OrderDateStr: string;
  OrderDiscountAmt: number;
  OrderDist: string;
  OrderEmailAddress: string;
  OrderGstType: number;
  OrderID: number;
  OrderModeOfDel: string;
  OrderNo: number;
  OrderPhoneNo: string;
  OrderPin: string;
  OrderPlace: string;
  OrderPostOffice: string;
  OrderRemarks: string;
  OrderSource: string;
  OrderState: string;
  PartyClientID: number;
  PartyID: number;
  PartyName: string;
  RefundAmt: number;
  RefundRemarks: string;
  Remarks: string;
  RofAmt: number;
  SGSTAmt: number;
  SeatNos: string;
  SvrBillNo: number;
  SvrCode: number;
  TotAmount: number;
  TotItemDiscount: number;
  TransactionNo: string;
  UPIPay: number;
  UserAutoID: number;
  UserCode: string;
  VehicleNo: string;
}

export interface InventoryItemInterface {
  ALQTY: number;
  ActionType: number;
  AddedBy: number;
  BARCODEID: string;
  BATCHNO: string;
  Barcode: string;
  CLIENTPRFIX: string;
  CLIENTTRANSID: string;
  CatID: number;
  Category: string;
  ClrGroup: string;
  Cost: number;
  CostPrice: number;
  CounterNo: string;
  DGID: number;
  DGNDX: number;
  DROPPED: boolean;
  Department: string;
  DesignCode: string;
  DesignNo: number;
  DisplayGrp: string;
  EXPDTYN: boolean;
  FinalStock: number;
  FolderName: string;
  FreeQty: number;
  GENNAME: string;
  GSTITMCD: number;
  IColor: string;
  ID: number;
  ISize: string;
  Icompany: string;
  ImageDescription: string;
  ImageFile: string | null;
  ImageFiles: string | null;
  ImagePath: string;
  IsActive: boolean;
  LastDate: string;
  LastRate: number;
  LoosQty: number;
  LooseRate: number;
  MRP: number;
  Material: string;
  NUMBERPERCASE: number;
  NUMBERPERCASE1: number;
  ORGAUTOID: number;
  ORGCODE: number;
  OldHsnCode: number;
  OrderCesPer: number;
  PLUCODE: string;
  PNID: number;
  PRERSUPL: string;
  ProductBL: string;
  ProductDupatta: string;
  ProductGroup: string;
  ProductLining: string;
  ProductSL: string;
  ProductStyle: string;
  ProductTL: string;
  ProductWork: string;
  PrtRecQty: number;
  PurPrice: number;
  QryStr: string;
  QtnMargPer: number;
  QtnMargRate: number;
  RTLProfitPer: number;
  RegistrationID: number;
  Remarks1: string;
  Remarks2: string;
  Remarks3: string;
  STKCGSTRate: number;
  STKDIVNUM: number;
  STKGSTRate: number;
  STKHSNCode: number;
  STKIGSTRate: number;
  STKSGSTRate: number;
  STKSVRSTOCK: number;
  STOCKCOLOR: string;
  SUPLID: number;
  SVRENTID: number;
  SVRSTKID: number;
  SVRUPDYN: number;
  SaleDisPer: number;
  SalePrice: number;
  SizeID: number;
  Stk_Opn_Rate: number;
  Stk_opn: number;
  Stk_opn2: number;
  StockType: string;
  SubCatID: number;
  SubCategory: string;
  TYPE: string;
  TransactionID: number;
  UNITS: string;
  UNITS1: string;
  VatMaster: string;
  VatMasterOut: string;
  WSPrice: number;
  WSProfitPer: number;
  YouTubeLink: string;
  billno: number;
  itm_CD: number;
  itm_NAM: string;
  ordertype: number;
  pickerValue: string;
  subgrp: string;
  total: number;
}

export type TableInfoType = {
  TBLAutoID: number;
  TableName: string;
  TblLocation: string;
  TBLFloor: string;
  NofSeats: number;
};

export type TableStatusType = {
  ActionType: number;
  OrderID: number;
  SeatNos: string;
  SeatType: string;
  TBLAutoID: number;
  TableName: string;
  EntryDateTimeStr: string;
};

export type PrinterInterface = {
  PrinterID: number;
  PrinterOSName: string;
  PrinterLocationName: string;
  IsDropped: boolean;
};
